### ISSUE TITLE
Lightwalletd Crashes on getBlockFromRPC

### ISSUE THREAD

**Issue by pacu** [zcash/lightwalletd#407]
**What is the bug?**
Lightwalletd crashes and becomes unreachable. 

Logs:
````
lightwalletd_1     | 2022-07-28T02:43:37.996112745Z {"app":"lightwalletd","level":"info","msg":"Waiting for block: 1752846","time":"2022-07-28T02:43:37Z"}
lightwalletd_1     | 2022-07-28T02:44:43.853605881Z {"app":"lightwalletd","level":"info","msg":"Waiting for block: 1752847","time":"2022-07-28T02:44:43Z"}
lightwalletd_1     | 2022-07-28T02:45:33.930886309Z panic: runtime error: index out of range [7] with length 7
lightwalletd_1     | 2022-07-28T02:45:33.930959216Z 
lightwalletd_1     | 2022-07-28T02:45:33.930968175Z goroutine 141 [running]:
lightwalletd_1     | 2022-07-28T02:45:33.937735609Z github.com/zcash/lightwalletd/common.getBlockFromRPC(0x1abf0f)
lightwalletd_1     | 2022-07-28T02:45:33.937772803Z     /go/src/github.com/zcash/lightwalletd/common/common.go:296 +0x7da
lightwalletd_1     | 2022-07-28T02:45:33.937781457Z github.com/zcash/lightwalletd/common.BlockIngestor(0x6d8ba6?, 0x0)
lightwalletd_1     | 2022-07-28T02:45:33.937912566Z     /go/src/github.com/zcash/lightwalletd/common/common.go:370 +0x477
lightwalletd_1     | 2022-07-28T02:45:33.937926267Z created by github.com/zcash/lightwalletd/cmd.startServer
lightwalletd_1     | 2022-07-28T02:45:33.938063369Z     /go/src/github.com/zcash/lightwalletd/cmd/root.go:249 +0x17c5
````

**Additional context**
I noticed this when syncing a long dated wallet I use for testing. It possibly has nothingh to do but my wallet was requesting blocks around the 800 thousands 

Possible related issue:
https://github.com/zcash/lightwalletd/issues/400

**Comment by pacu** [comment]
closing in favor of #408
